export const listOfWords = [
  { text: "Cześć", image: "img_czesc.jpg" },
  { text: "Jola", image: "img_jola.jpg" },
  { text: "Aneta", image: "img_item_aneta.jpg" },
  { text: "Wiki", image: "img_wiktoria.jpg" },
  { text: "Wyjechać po Ciebie?", image: "img_wyjechac_po_ciebie.jpg" },
  { text: "Czy ugotowac ziemniaki?", image: "img_wstawilem_ziemniaki.jpg" },
  { text: "Pije kawe", image: "pije_kawe.jpg" },
  { text: "Chleb", image: "img_chleb.jpg" },
  { text: "Zostawiłem klucze", image: "img_zostawilem_klucze.jpg" },
  { text: "Jestem u kazika", image: "img_jestem_u_kazika.jpg" },
  { text: "Gram w pasjansa", image: "img_gram_w_pasjansa.jpg" },
  { text: "Dziękuje", image: "img_dziekuje.jpg" },
  { text: "Dobrze", image: "img_dobrze.jpg" },
  { text: "Układam kostke", image: "img_ukladam_kostke.jpg" },
  { text: "Kupiłem chleb", image: "img_kupilem_chleb.jpg" },
  { text: "Ania", image: "img_ania.jpg" },
  { text: "Krzyś", image: "img_krzys.jpg" },
  { text: "Mariusz", image: "img_mariusz.jpg" },
  { text: "Piotrek", image: "img_piotrek.jpg" },
  { text: "Tadek", image: "img_tadek.jpg" },
  { text: "Tomek", image: "img_tomek.jpg" },
  { text: "Zuzia", image: "img_zuzia.jpg" },
  { text: "Adaś", image: "img_adas.jpg" },
  { text: "Oglądam telewizje", image: "img_ogladam_telewizje.jpg" },
  { text: "Barwy szczęscia", image: "img_barwy_szczescia.jpg" },
  { text: "M jak miłośc", image: "img_m_jak_milosc.jpg" },
  { text: "Wstawiłem ziemniaki", image: "img_wstawilem_ziemniaki.jpg" },
  // { text: "Upiekłaś ciastka", image: "img_ukladam_kostke.jpg" },
  { text: "ziemniaki", image: "img_czy_obraz_ziemniaki.jpg" },
  
  // 03- narzedzia
  
  { text: "Układam drzewo", image: "03-narzedzia/img_drewno.jpg" },
  { text: "Zbieram grzyby", image: "03-narzedzia/img_grzyby.jpg" },
  { text: "Miernik", image: "03-narzedzia/img_miernik.jpg" },
  { text: "Motocykl", image: "03-narzedzia/img_motocykl.jpg" },
  { text: "Sauna", image: "03-narzedzia/img_sauna.jpg" },
  { text: "Szczypce", image: "03-narzedzia/img_szczypce.jpg" },
  { text: "Wiertarka", image: "03-narzedzia/img_wiertarka.jpg" },
  { text: "Klucz", image: "03-narzedzia/img_klucz.jpg" },
  { text: "Przedłużacz", image: "03-narzedzia/img_przedluzacz.jpg" },
  { text: "Szlifierka", image: "03-narzedzia/img_szlifierka.jpg" },
  { text: "O której będziesz?", image: "img_o_ktorej_bedziesz_zegarek.jpg" },
  { text: "Kosze trawe", image: "img_kosze_trawe.jpg" },
  { text: "Woże drzewo", image: "img_woze_drzewo.jpg" },
  { text: "Naprawiam motor", image: "img_naprawiam_motor.jpg" },
  { text: "Piła", image: "img_pila.jpg" },
  { text: "naprawiam samochód", image: "img_naprawiam_samochod.jpg" },
  { text: "Na papierosie", image: "img_papierosy.jpg" },
  { text: "Spotkałem", image: "img_spotkalem.jpg" },
  { text: "Wracam o", image: "img_wracam_o.jpg" },
  { text: "Dzwonił", image: "img_dzwonil.jpg" },
  { text: "Zakupy", image: "img_zakupy.jpg" },
  
  
  // do opisania
  // { text: "Wiertarka", image: "img_wiertarka.jpg" },
  // {
  //   text: "Rodzina i znajomi",
  //   image: "img_category_rodzina_i_znajomi.jpg"
  // },
  // { text: "Kategoria - Co robie?", image: "img_co_robie.jpg" },
  // { text: "Jestem", image: "img_czesc.jpg" },
  // { text: "W garażu", image: "img_czesc.jpg" },
  // { text: "Niedlugo", image: "img_czesc.jpg" },
];
